
## AWS Configuration

host: mysite.com
port: 8080

aws:
    region: us-east
  
  # S3 Configuration - TODO - add other basic S3 Config Settings
    s3:
      defaultBucket: shagwood-io
  
  
    #SQS Configuration - TODO - add ability to specify more queue infomation
    sqs:
        queues:
            - name: "FileSavedQueue"
        produces: true
        consumers:
            - queue: FileSavedQueue
              handler: com.evidint.app.LogOutputHandler
              threads: 3
 
 
    #DynamoDb Config - The package prefix to scan for DynamoDb mapper annotations
    dynamo:
       packageScanPrefix: "io.microgenie"
       
    # Kinesis Event - Pub / Sub Configuration
    kinesis:
       - topic: "FileSavedAuditEvent"
         shards: 3

    
## Standard Dropwizard Configurations

# Server Settings
server:
  applicationConnectors:
    - type: http
      port: 8080

  adminConnectors:
    - type: http
      port: 8081


# Logging settings.
logging:

  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: INFO

  # Logger-specific levels.
  loggers:

    # Sets the level for 'com.example.app' to DEBUG.
    io.microgenie.dw: DEBUG

  appenders:
    - type: console